# problem statement:-1]

In [1]:
# 1) Prepare a classification model using SVM for salary data 


# Data Description:

# age -- age of a person

# workclass	-- A work class is a grouping of work 

# education	-- Education of an individuals	

# maritalstatus -- Marital status of an individulas	

# occupation	 -- occupation of an individuals
# relationship -- 	

# race --  Race of an Individual

# sex --  Gender of an Individual

# capitalgain --  profit received from the sale of an investment	

# capitalloss	-- A decrease in the value of a capital 
# asset
# hoursperweek -- number of hours work per week	

# native -- Native of an individual

# Salary -- salary of an individual


# import the important library:-

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df1=pd.read_csv("SalaryData_Test(1).csv")
df2=pd.read_csv("SalaryData_Train(1).csv")

In [4]:
df=df1.append(df2)

In [5]:
df.shape

(45221, 14)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45221 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            45221 non-null  int64 
 1   workclass      45221 non-null  object
 2   education      45221 non-null  object
 3   educationno    45221 non-null  int64 
 4   maritalstatus  45221 non-null  object
 5   occupation     45221 non-null  object
 6   relationship   45221 non-null  object
 7   race           45221 non-null  object
 8   sex            45221 non-null  object
 9   capitalgain    45221 non-null  int64 
 10  capitalloss    45221 non-null  int64 
 11  hoursperweek   45221 non-null  int64 
 12  native         45221 non-null  object
 13  Salary         45221 non-null  object
dtypes: int64(5), object(9)
memory usage: 5.2+ MB


In [7]:
df.describe()

age   educationno   capitalgain   capitalloss  hoursperweek
count  45221.000000  45221.000000  45221.000000  45221.000000  45221.000000
mean      38.548086     10.118463   1101.454700     88.548617     40.938038
std       13.217981      2.552909   7506.511295    404.838249     12.007640
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       47.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   4356.000000     99.000000

In [8]:
df.dtypes

age               int64
workclass        object
education        object
educationno       int64
maritalstatus    object
occupation       object
relationship     object
race             object
sex              object
capitalgain       int64
capitalloss       int64
hoursperweek      int64
native           object
Salary           object
dtype: object

In [9]:
df.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

# Converting string value to int type for labels

In [10]:
from sklearn.preprocessing import LabelEncoder


In [11]:
cols=["workclass","education","maritalstatus","occupation","relationship","race","sex","native","Salary"]
df[cols]=df[cols].apply(LabelEncoder().fit_transform)


In [12]:
df.head()

age  workclass  education  educationno  maritalstatus  occupation  \
0   25          2          1            7              4           6   
1   38          2         11            9              2           4   
2   28          1          7           12              2          10   
3   44          2         15           10              2           6   
4   34          2          0            6              4           7   

   relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
0             3     2    1            0            0            40      37   
1             0     4    1            0            0            50      37   
2             0     4    1            0            0            40      37   
3             0     2    1         7688            0            40      37   
4             1     4    1            0            0            30      37   

   Salary  
0       0  
1       0  
2       1  
3       1  
4       0

In [13]:
df.describe()

age     workclass     education   educationno  maritalstatus  \
count  45221.000000  45221.000000  45221.000000  45221.000000   45221.000000   
mean      38.548086      2.204507     10.313217     10.118463       2.585148   
std       13.217981      0.958132      3.816992      2.552909       1.500460   
min       17.000000      0.000000      0.000000      1.000000       0.000000   
25%       28.000000      2.000000      9.000000      9.000000       2.000000   
50%       37.000000      2.000000     11.000000     10.000000       2.000000   
75%       47.000000      2.000000     12.000000     13.000000       4.000000   
max       90.000000      6.000000     15.000000     16.000000       6.000000   

         occupation  relationship          race           sex   capitalgain  \
count  45221.000000  45221.000000  45221.000000  45221.000000  45221.000000   
mean       5.969572      1.412684      3.680281      0.675062   1101.454700   
std        4.026444      1.597242      0.832361      0.468357   7506.511295   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      0.000000      4.000000      0.000000      0.000000   
50%        6.000000      1.000000      4.000000      1.000000      0.000000   
75%        9.000000      3.000000      4.000000      1.000000      0.000000   
max       13.000000      5.000000      4.000000      1.000000  99999.000000   

        capitalloss  hoursperweek        native        Salary  
count  45221.000000  45221.000000  45221.000000  45221.000000  
mean      88.548617     40.938038     35.431503      0.247849  
std      404.838249     12.007640      5.931380      0.431769  
min        0.000000      1.000000      0.000000      0.000000  
25%        0.000000     40.000000     37.000000      0.000000  
50%        0.000000     40.000000     37.000000      0.000000  
75%        0.000000     45.000000     37.000000      0.000000  
max     4356.000000     99.000000     39.000000      1.000000

In [14]:
X=df.drop("Salary",axis=1)
y=df["Salary"]

# Data standardization

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
scale_df=StandardScaler()
scale_df.fit(X)
X1=scale_df.transform(X)

# Splitting dataset into training set and testing set for better generalisation

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(X1,y,test_size=0.33,random_state=1)

In [19]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((30298, 13), (14923, 13), (30298,), (14923,))

# Running SVM with default hyperparameter

In [20]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix

In [21]:
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
acc=accuracy_score(y_test,y_pred)
print("accuracy_score:",acc)
print(confusion_matrix(y_test,y_pred))

accuracy_score: 0.8440662065268377
[[10476   710]
 [ 1617  2120]]


In [22]:
model=SVC(kernel="poly")
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
acc=accuracy_score(y_test,y_pred)
print("accuracy_score:",acc)
print(confusion_matrix(y_test,y_pred))

accuracy_score: 0.8404476311733565
[[10538   648]
 [ 1733  2004]]


In [23]:
model=SVC(kernel="linear")
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
acc=accuracy_score(y_test,y_pred)
print("accuracy_score:",acc)
print(confusion_matrix(y_test,y_pred))

accuracy_score: 0.8043288882932387
[[10852   334]
 [ 2586  1151]]
